site_name: Mario Torres
site_url: https://mariotorrestech.github.io/
repo_url: https://github.com/mariotorrestech/mariotorrestech.github.io
docs_dir: docs
site_dir: site

nav:
  - Home: index.md
  - About: about.md
  - Homelab:
      - Overview: homelab/index.md
      - PNPT: homelab/pnpt.md
  - Infrastructure: infrastructure/index.md

theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  icon:
    logo: fontawesome/solid/m
  favicon: assets/favicon.ico
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features: 
    - navigation.footer
    - navigation.top
    - toc.follow
    - toc.integrate

  
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/tmario/
